language: node_js
node_js:
- node
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAII3DW4OTGOFVOKBQ
  - secure: q+Ppx5GPzE9Oftz7+7FVEQmlxVJLJn7afMa36XD4mJgOHSpWCwrMHjgOPw9bWjoX2/+os9mnT254ZpzmjPwMOFh49cmv1j1W/h/7e7on8y99Yq6f9kMWkeE59iYNkc3vTD6YSjy60pCjOV3omkM3AT9SBFKOxL29VTmfMnAdi9MEBgWIlbohHvbvq+GidFbKyZOYHzmBHnNOhZDY3ZcEITqXlmIt6Zp5j5LYQT0DlK5oRcfHlQEwMJLzARMv1Wyx+wP+VpttB8lQYnQmE4Yxa6J5iXmCKWlWTTR/stYDczu0ImSacZ3QWu9zoJ1d/CSVgj6nbJ3PKbA3/D6kgEBALyj//KdjqafCendD8tcTOpHQUROSt+3UWcKeHSJoDupn+23SiA+GWgYg0DRbzr0ZFGNPDSjTyEmkLRsapaipSo2mygSc1F55UIJDl7SyTe7mpdCPUH5Uwbhn7jB+vqzh0F+ybmY6KzqU0gIt5IixNsdMuRurcMWVQmrR9FFfsFHH1xWyDkOjYyY+OAB12Cnrz8+GRSl+jUOrjqbMOn2QXb+YT1dy7onSSMt7kSS8ZMBaM2ul47LEoRmm4uclTOw5+x1Yh/c/hioermaPD6hiEOPdpRe9MrwhSK1Mjt82ZLieLPufrKwU4kMAhyaUk7B1ubCqwLGDlZfO4WaL2xVu4Is=
cache:
  directories:
  - node_modules
script:
- npm install -g serverless
- sls deploy
