deploy:
  provider: lambda
  function_name: bin-day
  region: eu-west-2
  role: arn:aws:iam::726980345866:role/service-role/lambda-tester
  runtime: nodejs6.10
  handler_name: handler
  access_key_id: AKIAIZZNXVPXG7HBYPNA
  secret_access_key:
    secure: BPzwlme8XtdLYP2EdPffYuicT0C4vmemNaQFwqimtGtTaItTVW+zar+BEBuu3b3TF7+jI3ldtPJTwAXoac8falI3NdbGYB5pr2Wi0xzE3H+YhZPtQDWKIJCwjqTGUcU1OsYpICkAS/Kb3x9VpDWgWjRil3yRGJXWB3/JUAhoYWDTjLynAiN79JHc51KuRJvxB02ojzg5QpVBaT4B+ZnTXaOtWSzje2a1skdpLxg9UU2y+TYOhnGBpogouuClPXE+UDyeEYdCGOWKddI26qiCdywiPXXh5vxX17O1uhsl/ov+jh2Uk52cj/cxZsiFDjOcBhMIzJxBCmgjrgQDwGM4V/4WyIQV6zv5XmRCIXWgqGeDXCCIe9c85khkVrq+Kt0RQyilIl5ehz2Bk30+AbHFd+l7qeT3agXAvsp9a4kl3cacZESwMpR1GMeJaLnWAhPSLfbvOjrVA8lUJ6wLrdXiYJFsEVBWgQlpwktJp2HcRP2xHYq7g66WxHM90Ufj0hU53G1I3jsgI2k/WRUNCnQqZV0WuaCvKc349BBqsDKWMcbkhOkWBhkfssa2iJlaKiAzktiQ46DKvFTP/jY9wGqZlnZTLKtvBV487lwOhXY4jS6u0HCEuBbvmRIS6l5D52KABmj5gwAnd7GckoUjUpNtvlPPqRJqdR3U9+D22rgGflM=
