service: bins
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: dev
  region: eu-west-2
functions:
  query-and-notify:
    handler: main.handler
    environment:
      ADDRESSUPRN: ${env:ADDRESSUPRN}
      IFTTTKEY: ${env:IFTTTKEY}
    events:
      - http:
          path: bins
          method: get